# Generated by Django 5.2.5 on 2025-10-09 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='suspension_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
