# Generated by Django 5.2.5 on 2025-10-08 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Stadium Name')),
                ('google_maps_embed_url', models.URLField(blank=True, null=True, verbose_name='Google Maps Embed URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('day_of_week', models.CharField(max_length=10, verbose_name='Day of Week')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('max_players', models.PositiveIntegerField(default=12, verbose_name='Max Players')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='matches.stadium', verbose_name='Stadium')),
            ],
        ),
    ]
