# Generated by Django 5.2.5 on 2025-10-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='google_maps_embed_url',
        ),
        migrations.AddField(
            model_name='stadium',
            name='google_maps_short_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
