# Generated by Django 5.2.5 on 2025-10-01 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_location_google_maps_embed_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='location_google_maps_url',
        ),
    ]
