# Generated by Django 5.2.5 on 2025-09-09 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_match_location_google_maps_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='qr_token',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
