# Generated by Django 5.2.5 on 2025-09-09 04:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_match_qr_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='qr_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
