# Generated by Django 5.2.5 on 2025-10-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_remove_match_location_google_maps_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='location_google_maps_embed_url',
        ),
        migrations.AddField(
            model_name='match',
            name='location_google_maps_short_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps Short URL'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='match',
            name='day_of_week',
            field=models.CharField(max_length=10, verbose_name='Day of Week'),
        ),
        migrations.AlterField(
            model_name='match',
            name='location_name',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='match',
            name='max_players',
            field=models.PositiveIntegerField(default=12, verbose_name='Max Players'),
        ),
        migrations.AlterField(
            model_name='match',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='match',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
