# Generated by Django 5.2.5 on 2025-08-26 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('joined', 'Joined'), ('left', 'Left')], default='joined', max_length=10)),
                ('status_time', models.DateTimeField(auto_now_add=True)),
                ('removed', models.BooleanField(default=False)),
                ('removed_time', models.DateTimeField(blank=True, null=True)),
                ('is_no_show', models.BooleanField(default=False)),
                ('no_show_reason', models.CharField(blank=True, choices=[('excused', 'Excused'), ('not_excused', 'Not Excused'), ('last_minute', 'Last Minute')], max_length=20, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
