# Generated by Django 5.2.5 on 2025-09-04 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='player',
            new_name='user',
        ),
    ]
