# Generated by Django 5.2.5 on 2025-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0002_rename_player_participation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_present',
            field=models.BooleanField(default=False),
        ),
    ]
