# Generated by Django 5.2.5 on 2025-10-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participation', '0003_participation_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='no_show_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
